import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import AuthProviders from "@/services/AuthProviders";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="carDoctorTheme">
      <body>
        <AuthProviders>
        <Navbar/>
        {children}
        <Footer/>
        </AuthProviders>
        </body>
    </html>
  )
}
